# Generated by Django 2.1.5 on 2019-01-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='姓名')),
                ('content', models.CharField(max_length=1024, verbose_name='详情')),
            ],
        ),
    ]
